version: '3.3'

services:

    nginx-php-fpm:
        image: richarvey/nginx-php-fpm
        container_name: nginx-php
        ports:
            - "7000:80"
            - "7443:443"
        volumes:
            - ./html:/var/www/html            
        restart: unless-stopped
